### ISSUE TITLE
Add a README.md to the repository

### ISSUE THREAD

**Issue by jenlampton** [rstvo14/plan_bay_area_2040_final_plan#10]
We should add some documentation.

**Comment by chadupham** [comment]
@jenlampton  Do you have recommendations for what type of documentation should be included here? @rstvo14 will be able to write it, if you give a quick outline of topics to cover in the readme.

**Comment by jenlampton** [comment]
In general I like to think about the README as a tool for future developers, so it should contain everything they need to know to pick up work on the site in the future. Here are a few ideas:
* something that said the site was generated from a Drupal 8 site (to explain the markup)
* anything we might need to now about how the translation widget works (and where/how to add languages, since that was left out before)
* anything else about how the css/js assets are managed? (are they compressed or aggregated or anything?)
* anything about how the PDF documents are managed?

It would also be nice to include a Credits section:
* Who owns the site (MTC)
* Who created the HTML version (Gustavo)

**Comment by rstvo14** [comment]
README file has been updated. For the Localize translation widget, I assumed a developer would not have the same access as MTC admin. Let me know if any more modifications are needed.

**Comment by jenlampton** [comment]
This looks great! 
I made 2 minor commits to add some markdown formatting, please pull when you get chance. 

Closing ticket :)
