### ISSUE TITLE
On the video page, in the "modal-body" for each of the video pop-ups, add title attribute.

### ISSUE THREAD

**Issue by rstvo14** [rstvo14/plan_bay_area_2040_final_plan#22]
On the video page, in the "modal-body" for each of the video pop-ups, add title="YouTube Video Player" in the <iframe> element.

**Comment by chadupham** [comment]
Gustavo. This does not appear to have been addressed. let me know if you had trouble with it, or unclear.

**Comment by chadupham** [comment]
Ooop. My bad. I was looking at the live 2040 website in a different tab. This issue is resolved. Closing ticket.
