### ISSUE TITLE
 For each of the images that has a pop-up window, including single images and carousels, rework relationship of images and captions.

### ISSUE THREAD

**Issue by rstvo14** [rstvo14/plan_bay_area_2040_final_plan#23]
For each of the images that has a pop-up window, including single images and carousels, we need to need to rework relationship of images and captions. use structure similar to sample below. Adjust css as needed to match existing styles after reworking the element wrappers. figure/figurecaption may add some default browser styles that may need to be overridden.

for carousels:
<div class="item">
  <figure>
    <a .... >
      <span class="sr-only">open image in pop-up</span>
      <img src="xyz.jpg" alt="">
    </a>
    <figcaption> Caption and image credit goes here. </figcaption>
  </figure>
</div>

**Comment by rstvo14** [comment]
Changes to main.css
Deleted display: table-caption from .thump .caption (line 2892). Would otherwise restrict text width and not fill entire figcaption container.

**Comment by rstvo14** [comment]
Looks like there is no need to further style figure/figurecaption CSS.

**Comment by chadupham** [comment]
Good work. Tedious. Thank you.
