### ISSUE TITLE
Add alt text to zoomable images

### ISSUE THREAD

**Issue by chadupham** [rstvo14/plan_bay_area_2040_final_plan#26]
For all zoomable images, alt text to the <img> element inside links. copy text from from caption.

**Comment by rstvo14** [comment]
Found an issue with image alt="Transit-oriented development in West Oakland allows residents to travel to San Francisco and other nearby cities easily." not filling the entire width of container like the rest of the images.

**Comment by chadupham** [comment]
I think this will solve it: remove display: table-cell from .thump .image {} on line 2876 of main.css

**Comment by rstvo14** [comment]
Yup, it solved it. Without causing other issues.
