### ISSUE TITLE
add aria-hidden="true" to all zoom icons.

### ISSUE THREAD

**Issue by chadupham** [rstvo14/plan_bay_area_2040_final_plan#27]
add aria-hidden="true" to all zoom icons. This is redundant for screen readers, since the image link also opens in pop-up.

**Comment by rstvo14** [comment]
Seems all zoom icons already have <i class="fa fa-search-plus" aria-hidden="true"></i> added to zoom icons.

**Comment by chadupham** [comment]
For the single images, add it to the anchor wrapper. aria-hidden true has already been set for the icon i element, but we should add it to the parent link. so that that link is hidden from screen readers. a bit redundant, I know. Let me know if still unclear.

**Comment by rstvo14** [comment]
Got it! I have updated all anchor wrappers for single images to include aria-hidden="true" .
