### ISSUE TITLE
Add skip to content link above header.

### ISSUE THREAD

**Issue by chadupham** [rstvo14/plan_bay_area_2040_final_plan#29]
Add a focusable skip to content link at top of all pages. (first element inside of body before page header)
<a href="#content" class="visually-hidden focusable skip-link">Skip to content</a>
And add <div id="content"></div> before the first <section> on every page.
Ensure this website has css for visually-hidden focusable skip-link. If not, you can copy from x12.org.

**Comment by chadupham** [comment]
You will also need to add the focus state CSS for these element.
From x12.org
.visually-hidden.focusable:active, .visually-hidden.focusable:focus {
    position: static !important;
    overflow: visible;
    clip: auto;
    width: auto;
    height: auto;
}

You will be able to test that it works by tabbing into the browser URL, then tabbing to the next link on the page which is our hidden skip to content link, which should become visible with focus.

**Comment by chadupham** [comment]
Oh I see it now.. it is appearing below the fixed header bar.  But... I think my mistake in the email, the target div is id="content"  not id="#content".  sorry for typo.

**Comment by rstvo14** [comment]
No problem. It has been updated.
