### ISSUE TITLE
Change sidebar header from p to an h2

### ISSUE THREAD

**Issue by chadupham** [rstvo14/plan_bay_area_2040_final_plan#35]
for all sidebar navigation, change the p tag to an h2 class="sidebar-header" and adjust css as needed to retain existing styling.

**Comment by chadupham** [comment]
On The Bay Area Today page, the class p sidebar-header has a mistake.. currently class sidebar=header. fix in code.

**Comment by rstvo14** [comment]
Fixed changed to sidebar-header

**Comment by chadupham** [comment]
Gus, the main topic in this issue is to change that p to and h2. This was not in my email list, but a new issue item here. You'll need to style the sidebar h2 to look like the current sidebar p.

**Comment by rstvo14** [comment]
h2 does add some extra padding after adjusting css styling.

**Comment by chadupham** [comment]
can you do margin: 0 and padding: 0 0 1.3rem; to match the existing? override the h2 style.

**Comment by rstvo14** [comment]
Adding margin: 0 to .sidebar h2 (line 2603) seems to do the trick. Identical padding to the original site.

**Comment by chadupham** [comment]
Looks really good. Closing this issue. Thanks Gustavo!
